name: Build Website (CI)

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  validate-html:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Check index.html
        run: |
          if [ -f index.html ]; then
            echo "index.html found"
          else
            echo "index.html missing"
            exit 1
          fi
